### ISSUE TITLE
Sometimes doesn't show any deps/devDeps

### ISSUE THREAD

**Issue by dylang** [zeke/npm-hub#1]
Loving this extension, thanks for bringing it up on [NodeUp](http://nodeup.com/).

I found some places where it doesn't work. I haven't had time to look into why:

Does not work:
https://github.com/facebook/flux
https://github.com/facebook/flux/tree/master/examples/flux-chat

Interesting, this one works:
https://github.com/facebook/react/tree/master/examples/todomvc-flux

**Comment by boulosdib** [comment]
I love this extension as well and the issue remains. I submitted a pull request recently.
 
It seems if package.json does not include dependencies, the extension exits before processing  devDependencies,  However  if an empty dependencies object is included, it shows devDependencies as in https://github.com/segmentio/analytics.js.

**Comment by zeke** [comment]
Hey @dylang sorry I missed this. Only 19 months late! I wasn't subscribed to activity on this repo. :see_no_evil: 

I've updated the extension and this should be fixed.
