### ISSUE TITLE
Versions don't show

### ISSUE THREAD

**Issue by selfrefactor** [zeke/npm-hub#16]
First, congrats on the nice idea. The extension is a must-have.

My issue is that I can see the versions of the dependencies only if I use the extension as unpacked extension.
If I use the version from Chrome Web Store, then I cannot see the versions.

I tested it on two browsers: Chromium 53 and Chrome 55 under Ubuntu 16  
For both browsers, the result is the same.

On a side-note, Chrome cries a warning:

`Unrecognized manifest key 'applications'`

when I upload the files.

**Comment by zeke** [comment]
Huh. Can you show a screenshot illustrating the issue? Can you inspect the HTML of the failing case and paste it here?

**Comment by bfred-it** [comment]
`applications` is for Firefox; Chrome doesn't like it but it's not a problem.

**Comment by selfrefactor** [comment]
Here is the single dependency code when version is missing 

`<li><a href="https://npmjs.org/package/jasmine-json-test-reporter">jasmine-json-test-reporter</a>&nbsp;&nbsp;Write Jasmine test results to disk in JSON format <a href="http://ghub.io/jasmine-json-test-reporter">(repo)</a></li>`

and here is where it shows

`
<li><a href="https://npmjs.org/package/jasmine-json-test-reporter">jasmine-json-test-reporter</a>&nbsp;<code><small>1.0.0-beta</small></code>&nbsp;Write Jasmine test results to disk in JSON format <a href="http://ghub.io/jasmine-json-test-reporter">(repo)</a></li>`

There were no console.log messages related to the issue.

**Comment by bfred-it** [comment]
Ah, true, the version info was [added after 2.0.1](https://github.com/zeke/npm-hub/commits/master), which is the version currently on the store.

@zeke did you get around setting up the automated deploy? https://github.com/DrewML/chrome-webstore-upload-cli/issues/7

**Comment by zeke** [comment]
> did you get around setting up the automated deploy?

No, I didn't. I was more than happy to let @paulirish take over the publishing. :)

@bfred-it you should have access to everything now. You wanna give it a shot?

**Comment by bfred-it** [comment]
Ah true, forgot about that. I'll try this week

**Comment by bfred-it** [comment]
761a88ffe5430c672577238bf99dd7019e7c503e

**Comment by zeke** [comment]
👏
