### ISSUE TITLE
UI is broken with new experimental nav layout

### ISSUE THREAD

**Issue by knownasilya** [zeke/npm-hub#4]
The elements need to be appended to `.experiment-repo-nav` if the page has it.

Otherwise this is what it looks like:
![screen shot 2015-12-24 at 8 36 50 am](https://cloud.githubusercontent.com/assets/34726/11995143/859dc67a-aa19-11e5-99bd-9b6a0c175fb6.png)

**Comment by Derimagia** [comment]
Any chance of getting this fixed in the Extension? Really neat idea, but right now it's unusable. I'd prefer not to make a competing extension since you already did a great job minus this issue...

**Comment by Derimagia** [comment]
@knownasilya looks like this isn't being actively supported. 

OctoLinker is another awesome extension that's kind of similar. I recommend it: https://github.com/octo-linker/chrome-extension.

**Comment by knownasilya** [comment]
Yeah, already using it.

**Comment by knownasilya** [comment]
Maybe the owner could add us as collaborators?

**Comment by derimagia** [comment]
Looks like the owner made some change to the chrome plugin and it seems better now

**Comment by zeke** [comment]
Hey @derimagia and @knownasilya. Sorry I missed this thread, I've been traveling a lot lately. I did indeed publish a fix to the Chrome store about about a week ago. Is it working well for you?

**Comment by knownasilya** [comment]
Looks to be fixed. Thanks @zeke.
