### ISSUE TITLE
Browser warning

### ISSUE THREAD

**Issue by egoist** [zeke/npm-hub#6]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

<img width="1153" alt="2016-05-05 10 41 35" src="https://cloud.githubusercontent.com/assets/8784712/15046402/1014e78c-1312-11e6-90f7-d73d4edb5b74.png">

**Comment by zeke** [comment]
Thanks for reporting, @egoist. I've seen that for a while and didn't investigate what extension was causing it. I emailed [Crossrider](http://crossrider.com/developer) support about a workaround.
